title: <p align="center"> Abhishek Jaiswal </p>
logo: /assets/img/scan_photo.png
description:
  <p align="center">
  <a href="https://github.com/absrepo">GitHub</a>  
  <br>   
  I'm currently doing EPG Program from IIIT Bangalore
  <br>
  </p>

theme: jekyll-theme-minimal
