title: <p align="center"> Abhishek Jaiswal </p>
logo: /assets/img/scan_photo.png

description: 

<p align="center">
  <p align="center">
  
  <a href="https://github.com/absrepo">GitHub</a>
  
  <br>   
  I'm working doing EPG Program from IIIT Banaglore. 
  I have overall 14 years of experience in IT Industry.
  <br>
  </p>
  
  
theme: jekyll-theme-minimal
