title: <p align="center"> Abhishek Jaiswal </p>
logo: /assets/img/logo.png

description: 
  <br>   
  I'm working doing EPG Program from IIT Banaglore.
  I have overall 14 years of experience in IT Industry.
  <br>
  </p>
  
theme: jekyll-theme-minimal
